### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [renatoathaydes/mako-smarthome#1]
Hello!

I found this project from https://hackaday.com/2023/06/06/a-lightweight-smart-home-server/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by renatoathaydes** [comment]
Hi, the code in this project is meant for my own usage so I expect to change anything at any time. I keep it open so anyone is free to use parts of the code in their own solutions.
If you want to copy parts of the code for your own personal projects, feel free to do it, I don't think a license is required for you to do that. If you intend to use it for commercial purposes, then yeah, you wouldn't be able to use it as I don't intend to add a license here.
